// <auto-generated />
namespace ELearning.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deleteposts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteposts));
        
        string IMigrationMetadata.Id
        {
            get { return "201712230543346_deleteposts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
